### ISSUE TITLE
Non-assets included in nuget packages

### ISSUE THREAD

**Issue by lawrencedine** [EtchUK/Etch.OrchardCore.ModuleBoilerplate#2]
With the current folder structure when you package the module up into a Nuget package you find that files are included in the assembly which probably shouldn't be.

Here is an example from [Moov2.OrchardCore.Fields](https://github.com/moov2/Moov2.OrchardCore.Fields) after opening the Nuget package in dotPeek.

![image](https://user-images.githubusercontent.com/925349/57136457-da893500-6da4-11e9-8a67-f12e7db7d256.png)

I have spent some time trying to work around this issue but I've had to park it for now. I think a potential solution is changing the project structure so that the directory with the `.csproj` file in it doesn't have all those files. 

I also tried plugging in to the various properties seen in [OrchardCore.Module.Targets](https://github.com/OrchardCMS/OrchardCore/tree/dev/src/OrchardCore/OrchardCore.Module.Targets) (e.g.: `ModuleAssetExcludes` which excludes the `Assets/**`) without any success.

**Comment by peterkeating** [comment]
Resolved.
